In [21]:
import numpy as np
data = np.load('data.npy')
target = np.load('target.npy')

In [22]:
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline

pca = PCA(n_components=150,whiten=True,random_state=42)
svc = SVC(kernel='rbf')

model = make_pipeline(pca, svc)

In [23]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [24]:
model.fit(train_data,train_target)

Pipeline(steps=[('pca', PCA(n_components=150, random_state=42, whiten=True)),
                ('svc', SVC())])

In [25]:
predict = model.predict(test_data)

In [26]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(test_target,predict)
print(acc)

0.9310344827586207


In [27]:
from sklearn.metrics import classification_report

print(classification_report(test_target,predict,target_names=['Barack Obama', 'Donald Trump', 'George W Bush']))

               precision    recall  f1-score   support

 Barack Obama       0.90      0.90      0.90        10
 Donald Trump       0.92      0.92      0.92        13
George W Bush       1.00      1.00      1.00         6

     accuracy                           0.93        29
    macro avg       0.94      0.94      0.94        29
 weighted avg       0.93      0.93      0.93        29



In [32]:
from sklearn.metrics import confusion_matrix



matrix =confusion_matrix(test_target,predict)
print(matrix)

[[ 9  1  0]
 [ 1 12  0]
 [ 0  0  6]]


In [33]:
# disp = ConfusionMatrixDisplay(confusion_matrix=matrix,display_label=['Barack Obama', 'Donald Trump', 'George W Bush'])
# disp.plot()

In [34]:
# pip install --user --update scikit-learn

In [35]:
import joblib

joblib.dump(model,'SVM_face_rec.sav')

['SVM_face_rec.sav']